version: '2'

services:
  node:
    build: ./FoodtruckService/
    ports: 
      - "8082:8082"

  angular:
    restart: always
    build: ./angularApp/
    ports:
     - "8080:8080"
     - "81:80"
     - "442:443"
    depends_on:
     - "node"

